### ISSUE TITLE
Do the login page basic layout

### ISSUE THREAD

**Issue by jenniferasmar** [PatrickYoussef/SOEN341Project#12]
Start by the base layout of the login. 
Download React files that we need to run the code

Duration: 5 hours
Story points: 3

![image](https://user-images.githubusercontent.com/60263256/73618895-95768580-45f8-11ea-8dc2-7c4ac939d82f.png)

**Comment by Lorenzo001** [comment]
Need to add a border using BootStrap

**Comment by progmartin** [comment]
nice job!
we need an option to "post picture" too
